export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const signupConstants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
};

export const categoryConstants = {
  GET_ALL_CAT_REQUEST: "GET_ALL_CAT_REQUEST",
  GET_ALL_CAT_FAILURE: "GET_ALL_CAT_FAILURE",
  GET_ALL_CAT_SUCCESS: "GET_ALL_CAT_SUCCESS",
  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
};

export const courseConstants = {
  ADD_COURSE_REQUEST: "ADD_COURSE_REQUEST",
  ADD_COURSE_FAILURE: "ADD_COURSE_FAILURE",
  ADD_COURSE_SUCCESS: "ADD_COURSE_SUCCESS",
  GET_ALL_COURSE_REQUEST: "GET_ALL_COURSE_REQUEST",
  GET_ALL_COURSE_FAILURE: "GET_ALL_COURSE_FAILURE",
  GET_ALL_COURSE_SUCCESS: "GET_ALL_COURSE_SUCCESS",
  GET_COURSE_BY_ID_REQUEST: "GET_COURSE_BY_ID_REQUEST",
  GET_COURSE_BY_ID_FAILURE: "GET_COURSE_BY_ID_FAILURE",
  GET_COURSE_BY_ID_SUCCESS: "GET_COURSE_BY_ID_SUCCESS",
};

export const addModuleConstants = {
  ADD_MODULE_REQUEST: "ADD_MODULE_REQUEST",
  ADD_MODULE_FAILURE: "ADD_MODULE_FAILURE",
  ADD_MODULE_SUCCESS: "ADD_MODULE_SUCCESS",
};

export const addContentConstants = {
  ADD_CONTENT_REQUEST: "ADD_CONTENT_REQUEST",
  ADD_CONTENT_FAILURE: "ADD_CONTENT_FAILURE",
  ADD_CONTENT_SUCCESS: "ADD_CONTENT_SUCCESS",
};
